class Config:
    SECRET_KEY = 'SECRETEKEYFORAPP2'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///placement.db'
    SECURITY_PASSWORD_SALT='SOMESALTTOTASTEAPP'
    SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
    SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'