import os 

class Config:
    SECRET_KEY = 'SECRETEKEYFORAPP2'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
    SECURITY_PASSWORD_SALT='SOMESALTTOTASTEAPP'
    SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
    SECURITY_TOKEN_AUTHENTICATION_HEADER = 'Authentication-Token'
    CACHE_TYPE = 'RedisCache'
    REDIS_URL =os.environ.get('REDIS_URL')
    CACHE_REDIS_URL = REDIS_URL
    CACHE_DEFAULT_TIMEOUT=300
    MAIL_SERVER = 'localhost'
    MAIL_PORT = 1025
    MAIL_USE_TLS= False
    MAIL_USE_SSL = False 
    MAIL_USERNAME=None
    MAIL_PASSWORD = None 
    MAIL_DEFAULT_SENDER='admin@gmail.com'

